// This file is part of ecbyts/ECBT (Environmental & Occupational Core Byte Tools).
// Copyright (C) 2026 Calvin Stefan Iost
// Licensed under the GNU Affero General Public License v3.0 (AGPL-3.0-only).
// See LICENSE file or https://www.gnu.org/licenses/agpl-3.0.txt
//
// Project: ECBT (Environmental & Occupational Core Byte Tools)
// Version: 0.1-beta
// Architecture: Digital Twin Architecture (Blockchain + ML + LLM)
// Application: EHS & Mining
// Authorship: Calvin Stefan Iost
// Copyright (c) 2026 Calvin Stefan Iost

/* ================================================================
   SAO WATER PARAMETERS — Agua Matrix Parameter Catalog
   Parametros SAO de Agua — Catalogo de Parametros da Matriz Agua

   Maior catalogo de parametros do protocolo SAO (79 entradas).
   Cobre 9 subcategorias: hidrologia, fisico-quimica, metais,
   organicos, microbiologia, ecotoxicologia, limnologia,
   contaminantes emergentes e isotopos ambientais.

   Cada parametro segue o esquema padrao do SAO com campos de
   matriz, nivel (essential/recommended/specialized), subcategoria,
   referencias regulatorias e cenarios de aplicacao.
   ================================================================ */

/**
 * Water matrix parameters for the SAO taxonomy.
 * Parametros da matriz agua para a taxonomia SAO.
 *
 * Tiers:
 *   - essential:    Parametros minimos obrigatorios em qualquer monitoramento
 *   - recommended:  Parametros recomendados para investigacoes completas
 *   - specialized:  Parametros avancados para situacoes especificas
 *
 * @type {Array<{id: string, name: string, names: {en: string, es: string}, defaultUnitId: string, type: string, category: string, allowedCustomFields: string[], sao: {matrix: string, tier: string, subcategory: string, regulatoryRefs: string[], scenarios: string[]}}>}
 */
export const AGUA_PARAMETERS = [
    // ================================================================
    // HYDROLOGY — Hidrologia
    // Vazao, nivel d'agua, curva de permanencia
    // ================================================================

    {
        id: 'water_flow_rate',
        name: 'Vazao',
        names: { en: 'Flow Rate', es: 'Caudal' },
        defaultUnitId: 'L_s',
        type: 'SI',
        category: 'hydrogeology',
        allowedCustomFields: ['measurement_method'],
        sao: {
            matrix: 'agua',
            tier: 'essential',
            subcategory: 'hydrology',
            regulatoryRefs: ['CONAMA 357/2005', 'ANA'],
            scenarios: ['tailings_dam', 'mining_operations', 'routine_monitoring'],
        },
    },
    {
        id: 'water_level_surface',
        name: "Nivel d'Agua",
        names: { en: 'Water Level', es: 'Nivel de Agua' },
        defaultUnitId: 'm',
        type: 'SI',
        category: 'hydrogeology',
        allowedCustomFields: ['measurement_method'],
        sao: {
            matrix: 'agua',
            tier: 'essential',
            subcategory: 'hydrology',
            regulatoryRefs: ['ANA'],
            scenarios: ['tailings_dam', 'mining_operations', 'routine_monitoring', 'deforestation'],
        },
    },
    {
        id: 'hydraulic_conductivity',
        name: 'Condutividade Hidraulica (K)',
        names: { en: 'Hydraulic Conductivity (K)', es: 'Conductividad Hidraulica (K)' },
        defaultUnitId: 'cm_s',
        type: 'SI',
        category: 'hydrogeology',
        allowedCustomFields: ['measurement_method'],
        sao: {
            matrix: 'agua',
            tier: 'recommended',
            subcategory: 'hydrology',
            regulatoryRefs: [],
            scenarios: ['tailings_dam', 'mining_operations', 'chemical_accident'],
        },
    },
    {
        id: 'transmissivity',
        name: 'Transmissividade (T)',
        names: { en: 'Transmissivity (T)', es: 'Transmisividad (T)' },
        defaultUnitId: 'm2_day',
        type: 'SI',
        category: 'hydrogeology',
        allowedCustomFields: ['measurement_method'],
        sao: {
            matrix: 'agua',
            tier: 'recommended',
            subcategory: 'hydrology',
            regulatoryRefs: [],
            scenarios: ['tailings_dam', 'mining_operations'],
        },
    },
    {
        id: 'storativity',
        name: 'Coeficiente de Armazenamento (S)',
        names: { en: 'Storativity (S)', es: 'Coeficiente de Almacenamiento (S)' },
        defaultUnitId: 'decimal',
        type: 'SI',
        category: 'hydrogeology',
        allowedCustomFields: ['measurement_method'],
        sao: {
            matrix: 'agua',
            tier: 'recommended',
            subcategory: 'hydrology',
            regulatoryRefs: [],
            scenarios: ['tailings_dam', 'mining_operations'],
        },
    },

    // ================================================================
    // PHYSICOCHEMICAL — Fisico-quimicos
    // pH, OD, DBO, DQO, temperatura, turbidez, condutividade, etc.
    // ================================================================

    {
        id: 'water_ph',
        name: 'pH',
        names: { en: 'pH', es: 'pH' },
        defaultUnitId: 'pH',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['sample_depth', 'temperature'],
        sao: {
            matrix: 'agua',
            tier: 'essential',
            subcategory: 'physicochemical',
            regulatoryRefs: ['CONAMA 357/2005', 'CONAMA 396/2008'],
            scenarios: ['tailings_dam', 'oil_spill', 'chemical_accident', 'mining_operations', 'routine_monitoring'],
        },
    },
    {
        id: 'dissolved_oxygen',
        name: 'Oxigenio Dissolvido (OD)',
        names: { en: 'Dissolved Oxygen (DO)', es: 'Oxigeno Disuelto (OD)' },
        defaultUnitId: 'mg_L',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['sample_depth', 'temperature'],
        sao: {
            matrix: 'agua',
            tier: 'essential',
            subcategory: 'physicochemical',
            regulatoryRefs: ['CONAMA 357/2005'],
            scenarios: ['tailings_dam', 'oil_spill', 'mining_operations', 'deforestation', 'routine_monitoring'],
        },
    },
    {
        id: 'water_bod',
        name: 'DBO5,20',
        names: { en: 'BOD5,20', es: 'DBO5,20' },
        defaultUnitId: 'mg_L',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['sample_depth'],
        sao: {
            matrix: 'agua',
            tier: 'essential',
            subcategory: 'physicochemical',
            regulatoryRefs: ['CONAMA 357/2005', 'CONAMA 430/2011'],
            scenarios: ['routine_monitoring', 'mining_operations'],
        },
    },
    {
        id: 'water_cod',
        name: 'DQO',
        names: { en: 'COD', es: 'DQO' },
        defaultUnitId: 'mg_L',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['sample_depth'],
        sao: {
            matrix: 'agua',
            tier: 'essential',
            subcategory: 'physicochemical',
            regulatoryRefs: ['CONAMA 357/2005', 'CONAMA 430/2011'],
            scenarios: ['oil_spill', 'chemical_accident', 'routine_monitoring'],
        },
    },
    {
        id: 'water_temperature',
        name: 'Temperatura da Agua',
        names: { en: 'Water Temperature', es: 'Temperatura del Agua' },
        defaultUnitId: 'celsius',
        type: 'SI',
        category: 'physical',
        allowedCustomFields: ['sample_depth'],
        sao: {
            matrix: 'agua',
            tier: 'essential',
            subcategory: 'physicochemical',
            regulatoryRefs: ['CONAMA 357/2005'],
            scenarios: ['tailings_dam', 'oil_spill', 'mining_operations', 'routine_monitoring'],
        },
    },
    {
        id: 'water_turbidity',
        name: 'Turbidez',
        names: { en: 'Turbidity', es: 'Turbidez' },
        defaultUnitId: 'NTU',
        type: 'SI',
        category: 'physical',
        allowedCustomFields: ['sample_depth'],
        sao: {
            matrix: 'agua',
            tier: 'essential',
            subcategory: 'physicochemical',
            regulatoryRefs: ['CONAMA 357/2005'],
            scenarios: ['tailings_dam', 'mining_operations', 'deforestation', 'routine_monitoring'],
        },
    },
    {
        id: 'water_conductivity',
        name: 'Condutividade Eletrica',
        names: { en: 'Electrical Conductivity', es: 'Conductividad Electrica' },
        defaultUnitId: 'uS_cm',
        type: 'SI',
        category: 'physical',
        allowedCustomFields: ['sample_depth', 'temperature'],
        sao: {
            matrix: 'agua',
            tier: 'essential',
            subcategory: 'physicochemical',
            regulatoryRefs: ['CONAMA 396/2008'],
            scenarios: ['tailings_dam', 'mining_operations', 'routine_monitoring'],
        },
    },
    {
        id: 'total_dissolved_solids',
        name: 'Solidos Totais Dissolvidos (STD)',
        names: { en: 'Total Dissolved Solids (TDS)', es: 'Solidos Totales Disueltos (STD)' },
        defaultUnitId: 'mg_L',
        type: 'SI',
        category: 'physical',
        allowedCustomFields: ['sample_depth'],
        sao: {
            matrix: 'agua',
            tier: 'essential',
            subcategory: 'physicochemical',
            regulatoryRefs: ['CONAMA 357/2005', 'CONAMA 396/2008'],
            scenarios: ['tailings_dam', 'mining_operations', 'routine_monitoring'],
        },
    },
    {
        id: 'total_suspended_solids',
        name: 'Solidos Suspensos Totais (SST)',
        names: { en: 'Total Suspended Solids (TSS)', es: 'Solidos Suspendidos Totales (SST)' },
        defaultUnitId: 'mg_L',
        type: 'SI',
        category: 'physical',
        allowedCustomFields: ['sample_depth'],
        sao: {
            matrix: 'agua',
            tier: 'essential',
            subcategory: 'physicochemical',
            regulatoryRefs: ['CONAMA 357/2005', 'CONAMA 430/2011'],
            scenarios: ['tailings_dam', 'mining_operations', 'routine_monitoring'],
        },
    },
    {
        id: 'secchi_depth',
        name: 'Transparencia (Disco de Secchi)',
        names: { en: 'Transparency (Secchi Disk)', es: 'Transparencia (Disco de Secchi)' },
        defaultUnitId: 'm',
        type: 'SI',
        category: 'physical',
        allowedCustomFields: [],
        sao: {
            matrix: 'agua',
            tier: 'essential',
            subcategory: 'physicochemical',
            regulatoryRefs: ['CONAMA 357/2005'],
            scenarios: ['tailings_dam', 'deforestation', 'routine_monitoring'],
        },
    },
    {
        id: 'water_alkalinity',
        name: 'Alcalinidade Total',
        names: { en: 'Total Alkalinity', es: 'Alcalinidad Total' },
        defaultUnitId: 'mg_L',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['sample_depth'],
        sao: {
            matrix: 'agua',
            tier: 'essential',
            subcategory: 'physicochemical',
            regulatoryRefs: [],
            scenarios: ['tailings_dam', 'mining_operations', 'routine_monitoring'],
        },
    },
    {
        id: 'water_redox',
        name: 'Potencial Redox (Eh)',
        names: { en: 'Redox Potential (Eh)', es: 'Potencial Redox (Eh)' },
        defaultUnitId: 'mV',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['sample_depth', 'temperature'],
        sao: {
            matrix: 'agua',
            tier: 'essential',
            subcategory: 'physicochemical',
            regulatoryRefs: [],
            scenarios: ['tailings_dam', 'oil_spill', 'chemical_accident', 'mining_operations', 'routine_monitoring'],
        },
    },
    {
        id: 'ammonia_nitrogen',
        name: 'Nitrogenio Amoniacal',
        names: { en: 'Ammonia Nitrogen', es: 'Nitrogeno Amoniacal' },
        defaultUnitId: 'mg_L',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['sample_depth', 'detection_limit'],
        sao: {
            matrix: 'agua',
            tier: 'essential',
            subcategory: 'physicochemical',
            regulatoryRefs: ['CONAMA 357/2005'],
            scenarios: ['mining_operations', 'routine_monitoring'],
        },
    },
    {
        id: 'nitrate',
        name: 'Nitrato (NO3-)',
        names: { en: 'Nitrate (NO3-)', es: 'Nitrato (NO3-)' },
        defaultUnitId: 'mg_L',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['sample_depth', 'detection_limit'],
        sao: {
            matrix: 'agua',
            tier: 'essential',
            subcategory: 'physicochemical',
            regulatoryRefs: ['CONAMA 357/2005', 'CONAMA 396/2008'],
            scenarios: ['mining_operations', 'deforestation', 'routine_monitoring'],
        },
    },
    {
        id: 'nitrite',
        name: 'Nitrito (NO2-)',
        names: { en: 'Nitrite (NO2-)', es: 'Nitrito (NO2-)' },
        defaultUnitId: 'mg_L',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['sample_depth', 'detection_limit'],
        sao: {
            matrix: 'agua',
            tier: 'essential',
            subcategory: 'physicochemical',
            regulatoryRefs: ['CONAMA 357/2005'],
            scenarios: ['routine_monitoring'],
        },
    },
    {
        id: 'total_kjeldahl_nitrogen',
        name: 'Nitrogenio Total Kjeldahl (NTK)',
        names: { en: 'Total Kjeldahl Nitrogen (TKN)', es: 'Nitrogeno Total Kjeldahl (NTK)' },
        defaultUnitId: 'mg_L',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['sample_depth', 'detection_limit'],
        sao: {
            matrix: 'agua',
            tier: 'essential',
            subcategory: 'physicochemical',
            regulatoryRefs: ['CONAMA 357/2005'],
            scenarios: ['routine_monitoring', 'deforestation'],
        },
    },
    {
        id: 'total_phosphorus',
        name: 'Fosforo Total',
        names: { en: 'Total Phosphorus', es: 'Fosforo Total' },
        defaultUnitId: 'mg_L',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['sample_depth', 'detection_limit'],
        sao: {
            matrix: 'agua',
            tier: 'essential',
            subcategory: 'physicochemical',
            regulatoryRefs: ['CONAMA 357/2005'],
            scenarios: ['deforestation', 'routine_monitoring'],
        },
    },
    {
        id: 'orthophosphate',
        name: 'Ortofosfato',
        names: { en: 'Orthophosphate', es: 'Ortofosfato' },
        defaultUnitId: 'mg_L',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['sample_depth', 'detection_limit'],
        sao: {
            matrix: 'agua',
            tier: 'essential',
            subcategory: 'physicochemical',
            regulatoryRefs: ['CONAMA 357/2005'],
            scenarios: ['routine_monitoring'],
        },
    },

    // ================================================================
    // METALS_WATER — Metais em Agua
    // Arsenio, cadmio, cromo, cobre, mercurio, manganes, etc.
    // ================================================================

    {
        id: 'arsenic_water',
        name: 'Arsenio (As)',
        names: { en: 'Arsenic (As)', es: 'Arsenico (As)' },
        defaultUnitId: 'ug_L',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['sample_depth', 'detection_limit', 'cas_number'],
        sao: {
            matrix: 'agua',
            tier: 'essential',
            subcategory: 'metals_water',
            regulatoryRefs: ['CONAMA 357/2005', 'CONAMA 396/2008', 'CETESB 2021'],
            scenarios: ['tailings_dam', 'mining_operations', 'routine_monitoring'],
        },
    },
    {
        id: 'cadmium_water',
        name: 'Cadmio (Cd)',
        names: { en: 'Cadmium (Cd)', es: 'Cadmio (Cd)' },
        defaultUnitId: 'ug_L',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['sample_depth', 'detection_limit', 'cas_number'],
        sao: {
            matrix: 'agua',
            tier: 'essential',
            subcategory: 'metals_water',
            regulatoryRefs: ['CONAMA 357/2005', 'CONAMA 396/2008'],
            scenarios: ['tailings_dam', 'mining_operations', 'routine_monitoring'],
        },
    },
    {
        id: 'chromium_total_water',
        name: 'Cromo Total (Cr)',
        names: { en: 'Total Chromium (Cr)', es: 'Cromo Total (Cr)' },
        defaultUnitId: 'ug_L',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['sample_depth', 'detection_limit', 'cas_number'],
        sao: {
            matrix: 'agua',
            tier: 'essential',
            subcategory: 'metals_water',
            regulatoryRefs: ['CONAMA 357/2005', 'CONAMA 396/2008'],
            scenarios: ['tailings_dam', 'mining_operations', 'chemical_accident', 'routine_monitoring'],
        },
    },
    {
        id: 'copper_water',
        name: 'Cobre (Cu)',
        names: { en: 'Copper (Cu)', es: 'Cobre (Cu)' },
        defaultUnitId: 'ug_L',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['sample_depth', 'detection_limit', 'cas_number'],
        sao: {
            matrix: 'agua',
            tier: 'essential',
            subcategory: 'metals_water',
            regulatoryRefs: ['CONAMA 357/2005'],
            scenarios: ['tailings_dam', 'mining_operations', 'routine_monitoring'],
        },
    },
    {
        id: 'mercury_water',
        name: 'Mercurio (Hg)',
        names: { en: 'Mercury (Hg)', es: 'Mercurio (Hg)' },
        defaultUnitId: 'ug_L',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['sample_depth', 'detection_limit', 'cas_number'],
        sao: {
            matrix: 'agua',
            tier: 'essential',
            subcategory: 'metals_water',
            regulatoryRefs: ['CONAMA 357/2005', 'CONAMA 396/2008'],
            scenarios: ['tailings_dam', 'mining_operations', 'routine_monitoring'],
        },
    },
    {
        id: 'manganese_water',
        name: 'Manganes (Mn)',
        names: { en: 'Manganese (Mn)', es: 'Manganeso (Mn)' },
        defaultUnitId: 'ug_L',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['sample_depth', 'detection_limit', 'cas_number'],
        sao: {
            matrix: 'agua',
            tier: 'essential',
            subcategory: 'metals_water',
            regulatoryRefs: ['CONAMA 357/2005'],
            scenarios: ['tailings_dam', 'mining_operations', 'routine_monitoring'],
        },
    },
    {
        id: 'nickel_water',
        name: 'Niquel (Ni)',
        names: { en: 'Nickel (Ni)', es: 'Niquel (Ni)' },
        defaultUnitId: 'ug_L',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['sample_depth', 'detection_limit', 'cas_number'],
        sao: {
            matrix: 'agua',
            tier: 'essential',
            subcategory: 'metals_water',
            regulatoryRefs: ['CONAMA 357/2005'],
            scenarios: ['tailings_dam', 'mining_operations', 'routine_monitoring'],
        },
    },
    {
        id: 'lead_water',
        name: 'Chumbo (Pb)',
        names: { en: 'Lead (Pb)', es: 'Plomo (Pb)' },
        defaultUnitId: 'ug_L',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['sample_depth', 'detection_limit', 'cas_number'],
        sao: {
            matrix: 'agua',
            tier: 'essential',
            subcategory: 'metals_water',
            regulatoryRefs: ['CONAMA 357/2005', 'CONAMA 396/2008'],
            scenarios: ['tailings_dam', 'mining_operations', 'routine_monitoring'],
        },
    },
    {
        id: 'zinc_water',
        name: 'Zinco (Zn)',
        names: { en: 'Zinc (Zn)', es: 'Zinc (Zn)' },
        defaultUnitId: 'ug_L',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['sample_depth', 'detection_limit', 'cas_number'],
        sao: {
            matrix: 'agua',
            tier: 'essential',
            subcategory: 'metals_water',
            regulatoryRefs: ['CONAMA 357/2005'],
            scenarios: ['tailings_dam', 'mining_operations', 'routine_monitoring'],
        },
    },
    {
        id: 'iron_water',
        name: 'Ferro (Fe)',
        names: { en: 'Iron (Fe)', es: 'Hierro (Fe)' },
        defaultUnitId: 'mg_L',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['sample_depth', 'detection_limit', 'cas_number'],
        sao: {
            matrix: 'agua',
            tier: 'essential',
            subcategory: 'metals_water',
            regulatoryRefs: ['CONAMA 357/2005'],
            scenarios: ['tailings_dam', 'mining_operations', 'routine_monitoring'],
        },
    },
    {
        id: 'aluminum_water',
        name: 'Aluminio (Al)',
        names: { en: 'Aluminum (Al)', es: 'Aluminio (Al)' },
        defaultUnitId: 'mg_L',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['sample_depth', 'detection_limit', 'cas_number'],
        sao: {
            matrix: 'agua',
            tier: 'essential',
            subcategory: 'metals_water',
            regulatoryRefs: ['CONAMA 357/2005'],
            scenarios: ['tailings_dam', 'mining_operations', 'routine_monitoring'],
        },
    },
    {
        id: 'selenium_water',
        name: 'Selenio (Se)',
        names: { en: 'Selenium (Se)', es: 'Selenio (Se)' },
        defaultUnitId: 'ug_L',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['sample_depth', 'detection_limit', 'cas_number'],
        sao: {
            matrix: 'agua',
            tier: 'recommended',
            subcategory: 'metals_water',
            regulatoryRefs: ['CONAMA 357/2005'],
            scenarios: ['tailings_dam', 'mining_operations'],
        },
    },
    {
        id: 'barium_water',
        name: 'Bario (Ba)',
        names: { en: 'Barium (Ba)', es: 'Bario (Ba)' },
        defaultUnitId: 'mg_L',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['sample_depth', 'detection_limit', 'cas_number'],
        sao: {
            matrix: 'agua',
            tier: 'recommended',
            subcategory: 'metals_water',
            regulatoryRefs: ['CONAMA 357/2005', 'CONAMA 396/2008'],
            scenarios: ['mining_operations', 'oil_spill'],
        },
    },
    {
        id: 'chromium_hexavalent_water',
        name: 'Cromo Hexavalente (Cr6+)',
        names: { en: 'Hexavalent Chromium (Cr6+)', es: 'Cromo Hexavalente (Cr6+)' },
        defaultUnitId: 'ug_L',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['sample_depth', 'detection_limit', 'cas_number'],
        sao: {
            matrix: 'agua',
            tier: 'recommended',
            subcategory: 'metals_water',
            regulatoryRefs: ['CONAMA 357/2005', 'CONAMA 396/2008'],
            scenarios: ['chemical_accident', 'mining_operations'],
        },
    },

    // ================================================================
    // ORGANICS_WATER — Organicos em Agua
    // HPAs, TPH, pesticidas, fenois, O&G, surfactantes, COT
    // ================================================================

    {
        id: 'total_organic_carbon',
        name: 'Carbono Organico Total (COT)',
        names: { en: 'Total Organic Carbon (TOC)', es: 'Carbono Organico Total (COT)' },
        defaultUnitId: 'mg_L',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['sample_depth', 'detection_limit'],
        sao: {
            matrix: 'agua',
            tier: 'recommended',
            subcategory: 'organics_water',
            regulatoryRefs: ['CONAMA 357/2005'],
            scenarios: ['oil_spill', 'chemical_accident', 'routine_monitoring'],
        },
    },
    {
        id: 'sulfate_water',
        name: 'Sulfato (SO4 2-)',
        names: { en: 'Sulfate (SO4 2-)', es: 'Sulfato (SO4 2-)' },
        defaultUnitId: 'mg_L',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['sample_depth', 'detection_limit'],
        sao: {
            matrix: 'agua',
            tier: 'recommended',
            subcategory: 'organics_water',
            regulatoryRefs: ['CONAMA 357/2005'],
            scenarios: ['tailings_dam', 'mining_operations', 'routine_monitoring'],
        },
    },
    {
        id: 'sulfide_water',
        name: 'Sulfeto (S2-)',
        names: { en: 'Sulfide (S2-)', es: 'Sulfuro (S2-)' },
        defaultUnitId: 'mg_L',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['sample_depth', 'detection_limit'],
        sao: {
            matrix: 'agua',
            tier: 'recommended',
            subcategory: 'organics_water',
            regulatoryRefs: ['CONAMA 357/2005'],
            scenarios: ['mining_operations', 'oil_spill'],
        },
    },
    {
        id: 'chloride_water',
        name: 'Cloreto (Cl-)',
        names: { en: 'Chloride (Cl-)', es: 'Cloruro (Cl-)' },
        defaultUnitId: 'mg_L',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['sample_depth', 'detection_limit'],
        sao: {
            matrix: 'agua',
            tier: 'recommended',
            subcategory: 'organics_water',
            regulatoryRefs: ['CONAMA 357/2005'],
            scenarios: ['mining_operations', 'routine_monitoring'],
        },
    },
    {
        id: 'fluoride_water',
        name: 'Fluoreto (F-)',
        names: { en: 'Fluoride (F-)', es: 'Fluoruro (F-)' },
        defaultUnitId: 'mg_L',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['sample_depth', 'detection_limit'],
        sao: {
            matrix: 'agua',
            tier: 'recommended',
            subcategory: 'organics_water',
            regulatoryRefs: ['CONAMA 357/2005'],
            scenarios: ['mining_operations', 'routine_monitoring'],
        },
    },
    {
        id: 'cyanide_water',
        name: 'Cianeto Livre',
        names: { en: 'Free Cyanide', es: 'Cianuro Libre' },
        defaultUnitId: 'mg_L',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['sample_depth', 'detection_limit'],
        sao: {
            matrix: 'agua',
            tier: 'recommended',
            subcategory: 'organics_water',
            regulatoryRefs: ['CONAMA 357/2005'],
            scenarios: ['mining_operations', 'chemical_accident'],
        },
    },
    {
        id: 'phenols_water',
        name: 'Fenois Totais',
        names: { en: 'Total Phenols', es: 'Fenoles Totales' },
        defaultUnitId: 'mg_L',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['sample_depth', 'detection_limit'],
        sao: {
            matrix: 'agua',
            tier: 'recommended',
            subcategory: 'organics_water',
            regulatoryRefs: ['CONAMA 357/2005'],
            scenarios: ['oil_spill', 'chemical_accident', 'routine_monitoring'],
        },
    },
    {
        id: 'oil_grease_water',
        name: 'Oleos e Graxas (O&G)',
        names: { en: 'Oil & Grease (O&G)', es: 'Aceites y Grasas (O&G)' },
        defaultUnitId: 'mg_L',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['sample_depth', 'detection_limit'],
        sao: {
            matrix: 'agua',
            tier: 'recommended',
            subcategory: 'organics_water',
            regulatoryRefs: ['CONAMA 357/2005', 'CONAMA 430/2011'],
            scenarios: ['oil_spill', 'routine_monitoring'],
        },
    },
    {
        id: 'surfactants_water',
        name: 'Surfactantes (MBAS)',
        names: { en: 'Surfactants (MBAS)', es: 'Surfactantes (MBAS)' },
        defaultUnitId: 'mg_L',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['sample_depth', 'detection_limit'],
        sao: {
            matrix: 'agua',
            tier: 'recommended',
            subcategory: 'organics_water',
            regulatoryRefs: ['CONAMA 357/2005'],
            scenarios: ['routine_monitoring'],
        },
    },
    {
        id: 'pah_16_water',
        name: 'HPAs 16 (EPA)',
        names: { en: 'PAHs 16 (EPA)', es: 'HAPs 16 (EPA)' },
        defaultUnitId: 'ug_L',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: ['sample_depth', 'detection_limit', 'cas_number'],
        sao: {
            matrix: 'agua',
            tier: 'recommended',
            subcategory: 'organics_water',
            regulatoryRefs: ['CONAMA 357/2005', 'CETESB 2021'],
            scenarios: ['oil_spill', 'chemical_accident'],
        },
    },
    {
        id: 'tph_water',
        name: 'TPH (Hidrocarbonetos Totais de Petroleo)',
        names: { en: 'TPH (Total Petroleum Hydrocarbons)', es: 'TPH (Hidrocarburos Totales de Petroleo)' },
        defaultUnitId: 'mg_L',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: ['sample_depth', 'detection_limit', 'cas_number'],
        sao: {
            matrix: 'agua',
            tier: 'recommended',
            subcategory: 'organics_water',
            regulatoryRefs: ['CETESB 2021'],
            scenarios: ['oil_spill', 'chemical_accident'],
        },
    },
    {
        id: 'organochlorine_pesticides',
        name: 'Pesticidas Organoclorados',
        names: { en: 'Organochlorine Pesticides', es: 'Pesticidas Organoclorados' },
        defaultUnitId: 'ug_L',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: ['sample_depth', 'detection_limit', 'cas_number'],
        sao: {
            matrix: 'agua',
            tier: 'recommended',
            subcategory: 'organics_water',
            regulatoryRefs: ['CONAMA 357/2005'],
            scenarios: ['deforestation', 'routine_monitoring'],
        },
    },
    {
        id: 'glyphosate_water',
        name: 'Glifosato',
        names: { en: 'Glyphosate', es: 'Glifosato' },
        defaultUnitId: 'ug_L',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: ['sample_depth', 'detection_limit', 'cas_number'],
        sao: {
            matrix: 'agua',
            tier: 'recommended',
            subcategory: 'organics_water',
            regulatoryRefs: ['CONAMA 357/2005'],
            scenarios: ['deforestation', 'routine_monitoring'],
        },
    },

    // ================================================================
    // MICROBIOLOGY — Microbiologia
    // Coliformes, E. coli, cianobacterias, Chl-a, protozoarios
    // ================================================================

    {
        id: 'total_coliforms',
        name: 'Coliformes Totais',
        names: { en: 'Total Coliforms', es: 'Coliformes Totales' },
        defaultUnitId: 'NMP_100mL',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['sample_depth'],
        sao: {
            matrix: 'agua',
            tier: 'essential',
            subcategory: 'microbiology',
            regulatoryRefs: ['CONAMA 274/2000', 'CONAMA 357/2005'],
            scenarios: ['routine_monitoring', 'deforestation'],
        },
    },
    {
        id: 'ecoli_water',
        name: 'Escherichia coli',
        names: { en: 'Escherichia coli', es: 'Escherichia coli' },
        defaultUnitId: 'NMP_100mL',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['sample_depth'],
        sao: {
            matrix: 'agua',
            tier: 'essential',
            subcategory: 'microbiology',
            regulatoryRefs: ['CONAMA 274/2000', 'CONAMA 357/2005'],
            scenarios: ['routine_monitoring', 'deforestation'],
        },
    },
    {
        id: 'cyanobacteria_count',
        name: 'Contagem de Cianobacterias',
        names: { en: 'Cyanobacteria Count', es: 'Conteo de Cianobacterias' },
        defaultUnitId: 'cells_mL',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['sample_depth'],
        sao: {
            matrix: 'agua',
            tier: 'recommended',
            subcategory: 'microbiology',
            regulatoryRefs: ['CONAMA 357/2005', 'MS 888/2021'],
            scenarios: ['routine_monitoring', 'tailings_dam'],
        },
    },
    {
        id: 'microcystins',
        name: 'Microcistinas',
        names: { en: 'Microcystins', es: 'Microcistinas' },
        defaultUnitId: 'ug_L',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['sample_depth', 'detection_limit'],
        sao: {
            matrix: 'agua',
            tier: 'recommended',
            subcategory: 'microbiology',
            regulatoryRefs: ['MS 888/2021'],
            scenarios: ['routine_monitoring'],
        },
    },
    {
        id: 'chlorophyll_a',
        name: 'Clorofila-a',
        names: { en: 'Chlorophyll-a', es: 'Clorofila-a' },
        defaultUnitId: 'ug_L',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['sample_depth'],
        sao: {
            matrix: 'agua',
            tier: 'recommended',
            subcategory: 'microbiology',
            regulatoryRefs: ['CONAMA 357/2005'],
            scenarios: ['routine_monitoring', 'deforestation'],
        },
    },
    {
        id: 'protozoa_water',
        name: 'Protozoarios (Giardia/Cryptosporidium)',
        names: { en: 'Protozoa (Giardia/Cryptosporidium)', es: 'Protozoarios (Giardia/Cryptosporidium)' },
        defaultUnitId: 'cells_L',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['sample_depth', 'detection_limit'],
        sao: {
            matrix: 'agua',
            tier: 'specialized',
            subcategory: 'microbiology',
            regulatoryRefs: ['MS 888/2021'],
            scenarios: ['routine_monitoring'],
        },
    },

    // ================================================================
    // ECOTOX_WATER — Ecotoxicologia Aquatica
    // CL50, CE50, CENO, CEO, genotoxicidade
    // ================================================================

    {
        id: 'cl50_acute',
        name: 'CL50 (Concentracao Letal 50%)',
        names: { en: 'LC50 (Lethal Concentration 50%)', es: 'CL50 (Concentracion Letal 50%)' },
        defaultUnitId: 'mg_L_lethal',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['detection_limit', 'measurement_method'],
        sao: {
            matrix: 'agua',
            tier: 'recommended',
            subcategory: 'ecotox_water',
            regulatoryRefs: ['CONAMA 357/2005', 'CONAMA 430/2011', 'ABNT NBR 15088'],
            scenarios: ['oil_spill', 'chemical_accident', 'tailings_dam'],
        },
    },
    {
        id: 'ce50_acute',
        name: 'CE50 (Concentracao Efetiva 50%)',
        names: { en: 'EC50 (Effective Concentration 50%)', es: 'CE50 (Concentracion Efectiva 50%)' },
        defaultUnitId: 'mg_L_lethal',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['detection_limit', 'measurement_method'],
        sao: {
            matrix: 'agua',
            tier: 'recommended',
            subcategory: 'ecotox_water',
            regulatoryRefs: ['CONAMA 430/2011', 'ABNT NBR 12713'],
            scenarios: ['oil_spill', 'chemical_accident', 'tailings_dam'],
        },
    },
    {
        id: 'ceno_chronic',
        name: 'CENO (Concentracao de Efeito Nao Observado)',
        names: { en: 'NOEC (No Observed Effect Concentration)', es: 'CENO (Concentracion de Efecto No Observado)' },
        defaultUnitId: 'percent',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['measurement_method'],
        sao: {
            matrix: 'agua',
            tier: 'recommended',
            subcategory: 'ecotox_water',
            regulatoryRefs: ['CONAMA 430/2011'],
            scenarios: ['oil_spill', 'chemical_accident', 'tailings_dam', 'mining_operations'],
        },
    },
    {
        id: 'ceo_chronic',
        name: 'CEO (Concentracao de Efeito Observado)',
        names: { en: 'LOEC (Lowest Observed Effect Concentration)', es: 'CEO (Concentracion de Efecto Observado)' },
        defaultUnitId: 'percent',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['measurement_method'],
        sao: {
            matrix: 'agua',
            tier: 'recommended',
            subcategory: 'ecotox_water',
            regulatoryRefs: ['CONAMA 430/2011'],
            scenarios: ['oil_spill', 'chemical_accident', 'tailings_dam', 'mining_operations'],
        },
    },
    {
        id: 'genotoxicity_aquatic',
        name: 'Genotoxicidade Aquatica (Ensaio Cometa/MN)',
        names: { en: 'Aquatic Genotoxicity (Comet/MN Assay)', es: 'Genotoxicidad Acuatica (Ensayo Cometa/MN)' },
        defaultUnitId: 'percent',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['measurement_method'],
        sao: {
            matrix: 'agua',
            tier: 'specialized',
            subcategory: 'ecotox_water',
            regulatoryRefs: [],
            scenarios: ['chemical_accident', 'mining_operations'],
        },
    },

    // ================================================================
    // LIMNOLOGY — Limnologia
    // Estratificacao termica, termoclina, feopigmentos, N:P, BMWP
    // ================================================================

    {
        id: 'thermal_stratification',
        name: 'Estratificacao Termica',
        names: { en: 'Thermal Stratification', es: 'Estratificacion Termica' },
        defaultUnitId: 'celsius',
        type: 'SI',
        category: 'physical',
        allowedCustomFields: ['sample_depth'],
        sao: {
            matrix: 'agua',
            tier: 'recommended',
            subcategory: 'limnology',
            regulatoryRefs: [],
            scenarios: ['tailings_dam', 'routine_monitoring'],
        },
    },
    {
        id: 'np_ratio',
        name: 'Razao N:P',
        names: { en: 'N:P Ratio', es: 'Relacion N:P' },
        defaultUnitId: 'none',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: [],
        sao: {
            matrix: 'agua',
            tier: 'recommended',
            subcategory: 'limnology',
            regulatoryRefs: [],
            scenarios: ['routine_monitoring', 'deforestation'],
        },
    },
    {
        id: 'bmwp_index',
        name: 'Indice BMWP',
        names: { en: 'BMWP Index', es: 'Indice BMWP' },
        defaultUnitId: 'score',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: [],
        sao: {
            matrix: 'agua',
            tier: 'recommended',
            subcategory: 'limnology',
            regulatoryRefs: [],
            scenarios: ['mining_operations', 'deforestation', 'routine_monitoring'],
        },
    },
    {
        id: 'ept_index',
        name: 'Indice EPT (Ephemeroptera, Plecoptera, Trichoptera)',
        names: {
            en: 'EPT Index (Ephemeroptera, Plecoptera, Trichoptera)',
            es: 'Indice EPT (Ephemeroptera, Plecoptera, Trichoptera)',
        },
        defaultUnitId: 'percent',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: [],
        sao: {
            matrix: 'agua',
            tier: 'recommended',
            subcategory: 'limnology',
            regulatoryRefs: [],
            scenarios: ['mining_operations', 'deforestation', 'routine_monitoring'],
        },
    },
    {
        id: 'trophic_state_index',
        name: 'Indice de Estado Trofico (IET)',
        names: { en: 'Trophic State Index (TSI)', es: 'Indice de Estado Trofico (IET)' },
        defaultUnitId: 'score',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: [],
        sao: {
            matrix: 'agua',
            tier: 'essential',
            subcategory: 'limnology',
            regulatoryRefs: ['CETESB'],
            scenarios: ['routine_monitoring', 'deforestation'],
        },
    },
    {
        id: 'water_quality_index',
        name: 'Indice de Qualidade da Agua (IQA)',
        names: { en: 'Water Quality Index (WQI)', es: 'Indice de Calidad del Agua (ICA)' },
        defaultUnitId: 'score',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: [],
        sao: {
            matrix: 'agua',
            tier: 'essential',
            subcategory: 'limnology',
            regulatoryRefs: ['CETESB', 'ANA'],
            scenarios: ['routine_monitoring', 'tailings_dam', 'mining_operations'],
        },
    },

    // ================================================================
    // EMERGING — Contaminantes Emergentes
    // Farmacos, microplasticos, PFAS, BPA, retardantes de chama
    // ================================================================

    {
        id: 'pharmaceuticals_water',
        name: 'Farmacos (Diclofenaco, Ibuprofeno, etc.)',
        names: { en: 'Pharmaceuticals (Diclofenac, Ibuprofen, etc.)', es: 'Farmacos (Diclofenaco, Ibuprofeno, etc.)' },
        defaultUnitId: 'ng_L',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: ['sample_depth', 'detection_limit', 'cas_number'],
        sao: {
            matrix: 'agua',
            tier: 'specialized',
            subcategory: 'emerging',
            regulatoryRefs: [],
            scenarios: ['routine_monitoring'],
        },
    },
    {
        id: 'microplastics_water',
        name: 'Microplasticos',
        names: { en: 'Microplastics', es: 'Microplasticos' },
        defaultUnitId: 'particles_L',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: ['sample_depth', 'detection_limit'],
        sao: {
            matrix: 'agua',
            tier: 'specialized',
            subcategory: 'emerging',
            regulatoryRefs: [],
            scenarios: ['routine_monitoring', 'oil_spill'],
        },
    },
    {
        id: 'pfas_water',
        name: 'PFAS (Substancias Per/Polifluoroalquil)',
        names: { en: 'PFAS (Per/Polyfluoroalkyl Substances)', es: 'PFAS (Sustancias Per/Polifluoroalquil)' },
        defaultUnitId: 'ng_L',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: ['sample_depth', 'detection_limit', 'cas_number'],
        sao: {
            matrix: 'agua',
            tier: 'specialized',
            subcategory: 'emerging',
            regulatoryRefs: [],
            scenarios: ['chemical_accident', 'routine_monitoring'],
        },
    },
    {
        id: 'pcbs_water',
        name: 'PCBs (Bifenilas Policloradas)',
        names: { en: 'PCBs (Polychlorinated Biphenyls)', es: 'PCBs (Bifenilos Policlorados)' },
        defaultUnitId: 'ug_L',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: ['sample_depth', 'detection_limit', 'cas_number'],
        sao: {
            matrix: 'agua',
            tier: 'specialized',
            subcategory: 'emerging',
            regulatoryRefs: ['CONAMA 357/2005'],
            scenarios: ['chemical_accident'],
        },
    },
    {
        id: 'dioxins_furans_water',
        name: 'Dioxinas e Furanos (PCDD/PCDF)',
        names: { en: 'Dioxins and Furans (PCDD/PCDF)', es: 'Dioxinas y Furanos (PCDD/PCDF)' },
        defaultUnitId: 'ng_L',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: ['sample_depth', 'detection_limit', 'cas_number'],
        sao: {
            matrix: 'agua',
            tier: 'specialized',
            subcategory: 'emerging',
            regulatoryRefs: [],
            scenarios: ['chemical_accident'],
        },
    },
    {
        id: 'methylmercury_water',
        name: 'Metilmercurio (MeHg)',
        names: { en: 'Methylmercury (MeHg)', es: 'Metilmercurio (MeHg)' },
        defaultUnitId: 'ng_L',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: ['sample_depth', 'detection_limit', 'cas_number'],
        sao: {
            matrix: 'agua',
            tier: 'specialized',
            subcategory: 'emerging',
            regulatoryRefs: [],
            scenarios: ['mining_operations', 'tailings_dam'],
        },
    },
    {
        id: 'dgt_metals_water',
        name: 'Metais por DGT (Gradiente Difusivo em Filme Fino)',
        names: {
            en: 'DGT Metals (Diffusive Gradients in Thin Films)',
            es: 'Metales por DGT (Gradiente Difusivo en Pelicula Fina)',
        },
        defaultUnitId: 'ug_L',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: ['sample_depth', 'detection_limit'],
        sao: {
            matrix: 'agua',
            tier: 'specialized',
            subcategory: 'emerging',
            regulatoryRefs: [],
            scenarios: ['mining_operations', 'tailings_dam'],
        },
    },

    // ================================================================
    // ISOTOPES — Isotopos Ambientais
    // d13C, d2H, d34S, 87Sr/86Sr, razoes diagnosticas de HPAs
    // ================================================================

    {
        id: 'delta_13c',
        name: 'delta-13C (Carbono-13)',
        names: { en: 'delta-13C (Carbon-13)', es: 'delta-13C (Carbono-13)' },
        defaultUnitId: 'none',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['sample_depth', 'measurement_method'],
        sao: {
            matrix: 'agua',
            tier: 'specialized',
            subcategory: 'isotopes',
            regulatoryRefs: [],
            scenarios: ['oil_spill', 'mining_operations'],
        },
    },
    {
        id: 'delta_2h',
        name: 'delta-2H (Deuterio)',
        names: { en: 'delta-2H (Deuterium)', es: 'delta-2H (Deuterio)' },
        defaultUnitId: 'none',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['sample_depth', 'measurement_method'],
        sao: {
            matrix: 'agua',
            tier: 'specialized',
            subcategory: 'isotopes',
            regulatoryRefs: [],
            scenarios: ['mining_operations', 'tailings_dam'],
        },
    },
    {
        id: 'delta_34s',
        name: 'delta-34S (Enxofre-34)',
        names: { en: 'delta-34S (Sulfur-34)', es: 'delta-34S (Azufre-34)' },
        defaultUnitId: 'none',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['sample_depth', 'measurement_method'],
        sao: {
            matrix: 'agua',
            tier: 'specialized',
            subcategory: 'isotopes',
            regulatoryRefs: [],
            scenarios: ['mining_operations', 'tailings_dam'],
        },
    },
    {
        id: 'sr_isotope_ratio',
        name: 'Razao 87Sr/86Sr',
        names: { en: '87Sr/86Sr Ratio', es: 'Relacion 87Sr/86Sr' },
        defaultUnitId: 'none',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['sample_depth', 'measurement_method'],
        sao: {
            matrix: 'agua',
            tier: 'specialized',
            subcategory: 'isotopes',
            regulatoryRefs: [],
            scenarios: ['mining_operations', 'tailings_dam'],
        },
    },
    {
        id: 'pah_diagnostic_ratios',
        name: 'Razoes Diagnosticas de HPAs',
        names: { en: 'PAH Diagnostic Ratios', es: 'Relaciones Diagnosticas de HAPs' },
        defaultUnitId: 'none',
        type: 'SI',
        category: 'chemical',
        allowedCustomFields: ['measurement_method'],
        sao: {
            matrix: 'agua',
            tier: 'specialized',
            subcategory: 'isotopes',
            regulatoryRefs: [],
            scenarios: ['oil_spill'],
        },
    },
];
