// This file is part of ecbyts/ECBT (Environmental & Occupational Core Byte Tools).
// Copyright (C) 2026 Calvin Stefan Iost
// Licensed under the GNU Affero General Public License v3.0 (AGPL-3.0-only).
// See LICENSE file or https://www.gnu.org/licenses/agpl-3.0.txt
//
// Project: ECBT (Environmental & Occupational Core Byte Tools)
// Version: 0.1-beta
// Architecture: Digital Twin Architecture (Blockchain + ML + LLM)
// Application: EHS & Mining
// Authorship: Calvin Stefan Iost
// Copyright (c) 2026 Calvin Stefan Iost

/* ================================================================
   SAO PARAMS — Soil Matrix (Solo)
   Parametros SAO — Matriz de Solo

   Variaveis fisicas, quimicas, biologicas e de contaminacao
   do solo para monitoramento ambiental e remediacao.
   Referencia regulatoria principal: CONAMA 420/2009.
   ================================================================ */

/**
 * Soil matrix parameters for the SAO taxonomy.
 * Parametros da matriz solo para a taxonomia SAO.
 * @type {Array<Object>}
 */
export const SOLO_PARAMETERS = [
    // ─── ESSENTIAL ───────────────────────────────────────────

    // --- physical_soil (Propriedades fisicas do solo) ---
    {
        id: 'soil_sand',
        name: 'Areia (%)',
        names: { en: 'Sand (%)', es: 'Arena (%)' },
        defaultUnitId: 'percent',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: [],
        sao: {
            matrix: 'solo',
            tier: 'essential',
            subcategory: 'physical_soil',
            regulatoryRefs: ['ABNT NBR 7181'],
            scenarios: ['tailings_dam', 'mining_operations', 'deforestation', 'routine_monitoring'],
        },
    },
    {
        id: 'soil_silt',
        name: 'Silte (%)',
        names: { en: 'Silt (%)', es: 'Limo (%)' },
        defaultUnitId: 'percent',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: [],
        sao: {
            matrix: 'solo',
            tier: 'essential',
            subcategory: 'physical_soil',
            regulatoryRefs: ['ABNT NBR 7181'],
            scenarios: ['tailings_dam', 'mining_operations', 'deforestation', 'routine_monitoring'],
        },
    },
    {
        id: 'soil_clay',
        name: 'Argila (%)',
        names: { en: 'Clay (%)', es: 'Arcilla (%)' },
        defaultUnitId: 'percent',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: [],
        sao: {
            matrix: 'solo',
            tier: 'essential',
            subcategory: 'physical_soil',
            regulatoryRefs: ['ABNT NBR 7181'],
            scenarios: ['tailings_dam', 'mining_operations', 'deforestation', 'routine_monitoring'],
        },
    },
    {
        id: 'soil_bulk_density',
        name: 'Densidade Aparente',
        names: { en: 'Bulk Density', es: 'Densidad Aparente' },
        defaultUnitId: 'g_cm3',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: [],
        sao: {
            matrix: 'solo',
            tier: 'essential',
            subcategory: 'physical_soil',
            regulatoryRefs: ['EMBRAPA'],
            scenarios: ['tailings_dam', 'mining_operations', 'deforestation', 'routine_monitoring'],
        },
    },
    {
        id: 'soil_munsell_color',
        name: 'Cor Munsell',
        names: { en: 'Munsell Color', es: 'Color Munsell' },
        defaultUnitId: 'none',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: ['hue', 'value', 'chroma'],
        sao: {
            matrix: 'solo',
            tier: 'essential',
            subcategory: 'physical_soil',
            regulatoryRefs: ['Munsell Soil Color Charts'],
            scenarios: ['tailings_dam', 'mining_operations', 'deforestation', 'routine_monitoring'],
        },
    },

    // --- chemical_soil (Propriedades quimicas do solo) ---
    {
        id: 'soil_ph_h2o',
        name: 'pH (H2O)',
        names: { en: 'pH (H2O)', es: 'pH (H2O)' },
        defaultUnitId: 'pH',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: ['temperature'],
        sao: {
            matrix: 'solo',
            tier: 'essential',
            subcategory: 'chemical_soil',
            regulatoryRefs: ['EMBRAPA', 'CONAMA 420/2009'],
            scenarios: [
                'tailings_dam',
                'mining_operations',
                'deforestation',
                'chemical_accident',
                'routine_monitoring',
            ],
        },
    },
    {
        id: 'soil_ph_cacl2',
        name: 'pH (CaCl2)',
        names: { en: 'pH (CaCl2)', es: 'pH (CaCl2)' },
        defaultUnitId: 'pH',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: ['temperature'],
        sao: {
            matrix: 'solo',
            tier: 'essential',
            subcategory: 'chemical_soil',
            regulatoryRefs: ['EMBRAPA', 'IAC'],
            scenarios: ['tailings_dam', 'mining_operations', 'deforestation', 'routine_monitoring'],
        },
    },
    {
        id: 'soil_organic_matter',
        name: 'Materia Organica do Solo (MOS)',
        names: { en: 'Soil Organic Matter (SOM)', es: 'Materia Organica del Suelo (MOS)' },
        defaultUnitId: 'percent',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: [],
        sao: {
            matrix: 'solo',
            tier: 'essential',
            subcategory: 'chemical_soil',
            regulatoryRefs: ['EMBRAPA'],
            scenarios: ['tailings_dam', 'mining_operations', 'deforestation', 'routine_monitoring'],
        },
    },
    {
        id: 'soil_ctc',
        name: 'CTC (Capacidade de Troca Cationica)',
        names: { en: 'CEC (Cation Exchange Capacity)', es: 'CIC (Capacidad de Intercambio Cationico)' },
        defaultUnitId: 'cmolc_dm3',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: [],
        sao: {
            matrix: 'solo',
            tier: 'essential',
            subcategory: 'chemical_soil',
            regulatoryRefs: ['EMBRAPA'],
            scenarios: ['tailings_dam', 'mining_operations', 'deforestation', 'routine_monitoring'],
        },
    },
    {
        id: 'soil_sb',
        name: 'Soma de Bases (Ca + Mg + K)',
        names: { en: 'Sum of Bases (Ca + Mg + K)', es: 'Suma de Bases (Ca + Mg + K)' },
        defaultUnitId: 'cmolc_dm3',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: [],
        sao: {
            matrix: 'solo',
            tier: 'essential',
            subcategory: 'chemical_soil',
            regulatoryRefs: ['EMBRAPA'],
            scenarios: ['deforestation', 'mining_operations', 'routine_monitoring'],
        },
    },
    {
        id: 'soil_al_exchangeable',
        name: 'Aluminio Trocavel (Al3+)',
        names: { en: 'Exchangeable Aluminum (Al3+)', es: 'Aluminio Intercambiable (Al3+)' },
        defaultUnitId: 'cmolc_dm3',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: [],
        sao: {
            matrix: 'solo',
            tier: 'essential',
            subcategory: 'chemical_soil',
            regulatoryRefs: ['EMBRAPA'],
            scenarios: ['tailings_dam', 'mining_operations', 'deforestation', 'routine_monitoring'],
        },
    },
    {
        id: 'soil_base_saturation',
        name: 'Saturacao por Bases (V%)',
        names: { en: 'Base Saturation (V%)', es: 'Saturacion de Bases (V%)' },
        defaultUnitId: 'percent',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: [],
        sao: {
            matrix: 'solo',
            tier: 'essential',
            subcategory: 'chemical_soil',
            regulatoryRefs: ['EMBRAPA'],
            scenarios: ['deforestation', 'mining_operations', 'routine_monitoring'],
        },
    },
    {
        id: 'soil_al_saturation',
        name: 'Saturacao por Aluminio (m%)',
        names: { en: 'Aluminum Saturation (m%)', es: 'Saturacion de Aluminio (m%)' },
        defaultUnitId: 'percent',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: [],
        sao: {
            matrix: 'solo',
            tier: 'essential',
            subcategory: 'chemical_soil',
            regulatoryRefs: ['EMBRAPA'],
            scenarios: ['tailings_dam', 'mining_operations', 'deforestation', 'routine_monitoring'],
        },
    },
    {
        id: 'soil_p_available',
        name: 'Fosforo Disponivel (P)',
        names: { en: 'Available Phosphorus (P)', es: 'Fosforo Disponible (P)' },
        defaultUnitId: 'mg_kg',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: ['extraction_method'],
        sao: {
            matrix: 'solo',
            tier: 'essential',
            subcategory: 'chemical_soil',
            regulatoryRefs: ['EMBRAPA', 'IAC'],
            scenarios: ['deforestation', 'routine_monitoring'],
        },
    },

    // --- contamination_soil (Contaminantes do solo) ---
    {
        id: 'soil_as',
        name: 'Arsenio (As) no Solo',
        names: { en: 'Arsenic (As) in Soil', es: 'Arsenico (As) en Suelo' },
        defaultUnitId: 'mg_kg',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: ['detection_limit', 'extraction_method'],
        sao: {
            matrix: 'solo',
            tier: 'essential',
            subcategory: 'contamination_soil',
            regulatoryRefs: ['CONAMA 420/2009', 'CETESB 2021'],
            scenarios: ['tailings_dam', 'mining_operations', 'chemical_accident', 'routine_monitoring'],
        },
    },
    {
        id: 'soil_cd',
        name: 'Cadmio (Cd) no Solo',
        names: { en: 'Cadmium (Cd) in Soil', es: 'Cadmio (Cd) en Suelo' },
        defaultUnitId: 'mg_kg',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: ['detection_limit', 'extraction_method'],
        sao: {
            matrix: 'solo',
            tier: 'essential',
            subcategory: 'contamination_soil',
            regulatoryRefs: ['CONAMA 420/2009', 'CETESB 2021'],
            scenarios: ['tailings_dam', 'mining_operations', 'chemical_accident', 'routine_monitoring'],
        },
    },
    {
        id: 'soil_cr',
        name: 'Cromo (Cr) no Solo',
        names: { en: 'Chromium (Cr) in Soil', es: 'Cromo (Cr) en Suelo' },
        defaultUnitId: 'mg_kg',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: ['detection_limit', 'extraction_method'],
        sao: {
            matrix: 'solo',
            tier: 'essential',
            subcategory: 'contamination_soil',
            regulatoryRefs: ['CONAMA 420/2009', 'CETESB 2021'],
            scenarios: ['tailings_dam', 'mining_operations', 'chemical_accident', 'routine_monitoring'],
        },
    },
    {
        id: 'soil_cu',
        name: 'Cobre (Cu) no Solo',
        names: { en: 'Copper (Cu) in Soil', es: 'Cobre (Cu) en Suelo' },
        defaultUnitId: 'mg_kg',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: ['detection_limit', 'extraction_method'],
        sao: {
            matrix: 'solo',
            tier: 'essential',
            subcategory: 'contamination_soil',
            regulatoryRefs: ['CONAMA 420/2009', 'CETESB 2021'],
            scenarios: ['tailings_dam', 'mining_operations', 'chemical_accident', 'routine_monitoring'],
        },
    },
    {
        id: 'soil_hg',
        name: 'Mercurio (Hg) no Solo',
        names: { en: 'Mercury (Hg) in Soil', es: 'Mercurio (Hg) en Suelo' },
        defaultUnitId: 'mg_kg',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: ['detection_limit', 'extraction_method'],
        sao: {
            matrix: 'solo',
            tier: 'essential',
            subcategory: 'contamination_soil',
            regulatoryRefs: ['CONAMA 420/2009', 'CETESB 2021'],
            scenarios: ['tailings_dam', 'mining_operations', 'chemical_accident', 'routine_monitoring'],
        },
    },
    {
        id: 'soil_mn',
        name: 'Manganes (Mn) no Solo',
        names: { en: 'Manganese (Mn) in Soil', es: 'Manganeso (Mn) en Suelo' },
        defaultUnitId: 'mg_kg',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: ['detection_limit', 'extraction_method'],
        sao: {
            matrix: 'solo',
            tier: 'essential',
            subcategory: 'contamination_soil',
            regulatoryRefs: ['CONAMA 420/2009'],
            scenarios: ['tailings_dam', 'mining_operations', 'routine_monitoring'],
        },
    },
    {
        id: 'soil_ni',
        name: 'Niquel (Ni) no Solo',
        names: { en: 'Nickel (Ni) in Soil', es: 'Niquel (Ni) en Suelo' },
        defaultUnitId: 'mg_kg',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: ['detection_limit', 'extraction_method'],
        sao: {
            matrix: 'solo',
            tier: 'essential',
            subcategory: 'contamination_soil',
            regulatoryRefs: ['CONAMA 420/2009', 'CETESB 2021'],
            scenarios: ['tailings_dam', 'mining_operations', 'chemical_accident', 'routine_monitoring'],
        },
    },
    {
        id: 'soil_pb',
        name: 'Chumbo (Pb) no Solo',
        names: { en: 'Lead (Pb) in Soil', es: 'Plomo (Pb) en Suelo' },
        defaultUnitId: 'mg_kg',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: ['detection_limit', 'extraction_method'],
        sao: {
            matrix: 'solo',
            tier: 'essential',
            subcategory: 'contamination_soil',
            regulatoryRefs: ['CONAMA 420/2009', 'CETESB 2021'],
            scenarios: ['tailings_dam', 'mining_operations', 'chemical_accident', 'routine_monitoring'],
        },
    },
    {
        id: 'soil_zn',
        name: 'Zinco (Zn) no Solo',
        names: { en: 'Zinc (Zn) in Soil', es: 'Zinc (Zn) en Suelo' },
        defaultUnitId: 'mg_kg',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: ['detection_limit', 'extraction_method'],
        sao: {
            matrix: 'solo',
            tier: 'essential',
            subcategory: 'contamination_soil',
            regulatoryRefs: ['CONAMA 420/2009', 'CETESB 2021'],
            scenarios: ['tailings_dam', 'mining_operations', 'chemical_accident', 'routine_monitoring'],
        },
    },
    {
        id: 'soil_fe',
        name: 'Ferro (Fe) no Solo',
        names: { en: 'Iron (Fe) in Soil', es: 'Hierro (Fe) en Suelo' },
        defaultUnitId: 'mg_kg',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: ['detection_limit', 'extraction_method'],
        sao: {
            matrix: 'solo',
            tier: 'essential',
            subcategory: 'contamination_soil',
            regulatoryRefs: ['CONAMA 420/2009'],
            scenarios: ['tailings_dam', 'mining_operations', 'routine_monitoring'],
        },
    },
    {
        id: 'soil_al_total',
        name: 'Aluminio Total (Al) no Solo',
        names: { en: 'Total Aluminum (Al) in Soil', es: 'Aluminio Total (Al) en Suelo' },
        defaultUnitId: 'mg_kg',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: ['detection_limit', 'extraction_method'],
        sao: {
            matrix: 'solo',
            tier: 'essential',
            subcategory: 'contamination_soil',
            regulatoryRefs: ['CONAMA 420/2009'],
            scenarios: ['tailings_dam', 'mining_operations', 'routine_monitoring'],
        },
    },
    {
        id: 'soil_tph',
        name: 'TPH (Hidrocarbonetos Totais) no Solo',
        names: {
            en: 'TPH (Total Petroleum Hydrocarbons) in Soil',
            es: 'TPH (Hidrocarburos Totales de Petroleo) en Suelo',
        },
        defaultUnitId: 'mg_kg',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: ['detection_limit', 'fraction'],
        sao: {
            matrix: 'solo',
            tier: 'essential',
            subcategory: 'contamination_soil',
            regulatoryRefs: ['CONAMA 420/2009', 'CETESB 2021'],
            scenarios: ['chemical_accident', 'mining_operations', 'routine_monitoring'],
        },
    },
    {
        id: 'soil_btex',
        name: 'BTEX no Solo',
        names: { en: 'BTEX in Soil', es: 'BTEX en Suelo' },
        defaultUnitId: 'mg_kg',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: ['detection_limit', 'cas_number'],
        sao: {
            matrix: 'solo',
            tier: 'essential',
            subcategory: 'contamination_soil',
            regulatoryRefs: ['CONAMA 420/2009', 'CETESB 2021'],
            scenarios: ['chemical_accident', 'mining_operations', 'routine_monitoring'],
        },
    },
    {
        id: 'soil_classification',
        name: 'Classificacao Pedologica (SiBCS)',
        names: { en: 'Pedological Classification (SiBCS)', es: 'Clasificacion Pedologica (SiBCS)' },
        defaultUnitId: 'none',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: ['order', 'suborder', 'great_group'],
        sao: {
            matrix: 'solo',
            tier: 'essential',
            subcategory: 'physical_soil',
            regulatoryRefs: ['EMBRAPA SiBCS'],
            scenarios: ['tailings_dam', 'mining_operations', 'deforestation', 'routine_monitoring'],
        },
    },

    // ─── RECOMMENDED ─────────────────────────────────────────

    // --- physical_soil ---
    {
        id: 'soil_porosity',
        name: 'Porosidade Total',
        names: { en: 'Total Porosity', es: 'Porosidad Total' },
        defaultUnitId: 'cm3_cm3',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: [],
        sao: {
            matrix: 'solo',
            tier: 'recommended',
            subcategory: 'physical_soil',
            regulatoryRefs: ['EMBRAPA'],
            scenarios: ['tailings_dam', 'mining_operations', 'deforestation', 'routine_monitoring'],
        },
    },
    {
        id: 'soil_field_capacity',
        name: 'Capacidade de Campo',
        names: { en: 'Field Capacity', es: 'Capacidad de Campo' },
        defaultUnitId: 'cm3_cm3',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: [],
        sao: {
            matrix: 'solo',
            tier: 'recommended',
            subcategory: 'physical_soil',
            regulatoryRefs: ['EMBRAPA'],
            scenarios: ['deforestation', 'routine_monitoring'],
        },
    },
    {
        id: 'soil_wilting_point',
        name: 'Ponto de Murcha Permanente',
        names: { en: 'Permanent Wilting Point', es: 'Punto de Marchitez Permanente' },
        defaultUnitId: 'cm3_cm3',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: [],
        sao: {
            matrix: 'solo',
            tier: 'recommended',
            subcategory: 'physical_soil',
            regulatoryRefs: ['EMBRAPA'],
            scenarios: ['deforestation', 'routine_monitoring'],
        },
    },
    {
        id: 'soil_ksat',
        name: 'Condutividade Hidraulica Saturada (Ksat)',
        names: { en: 'Saturated Hydraulic Conductivity (Ksat)', es: 'Conductividad Hidraulica Saturada (Ksat)' },
        defaultUnitId: 'cm_s',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: [],
        sao: {
            matrix: 'solo',
            tier: 'recommended',
            subcategory: 'physical_soil',
            regulatoryRefs: ['EMBRAPA', 'ABNT NBR 14545'],
            scenarios: ['tailings_dam', 'mining_operations', 'chemical_accident', 'routine_monitoring'],
        },
    },
    {
        id: 'soil_penetration_resistance',
        name: 'Resistencia a Penetracao',
        names: { en: 'Penetration Resistance', es: 'Resistencia a la Penetracion' },
        defaultUnitId: 'MPa',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: ['depth_interval'],
        sao: {
            matrix: 'solo',
            tier: 'recommended',
            subcategory: 'physical_soil',
            regulatoryRefs: ['ASAE S313.3'],
            scenarios: ['mining_operations', 'deforestation', 'routine_monitoring'],
        },
    },
    {
        id: 'soil_aggregate_stability',
        name: 'Estabilidade de Agregados',
        names: { en: 'Aggregate Stability', es: 'Estabilidad de Agregados' },
        defaultUnitId: 'percent',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: [],
        sao: {
            matrix: 'solo',
            tier: 'recommended',
            subcategory: 'physical_soil',
            regulatoryRefs: ['EMBRAPA'],
            scenarios: ['deforestation', 'mining_operations', 'routine_monitoring'],
        },
    },

    // --- chemical_soil ---
    {
        id: 'soil_h_al',
        name: 'Acidez Potencial (H+Al)',
        names: { en: 'Potential Acidity (H+Al)', es: 'Acidez Potencial (H+Al)' },
        defaultUnitId: 'cmolc_dm3',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: [],
        sao: {
            matrix: 'solo',
            tier: 'recommended',
            subcategory: 'chemical_soil',
            regulatoryRefs: ['EMBRAPA'],
            scenarios: ['tailings_dam', 'mining_operations', 'deforestation', 'routine_monitoring'],
        },
    },
    {
        id: 'soil_micronutrients',
        name: 'Micronutrientes (Fe, Mn, Zn, Cu, B)',
        names: { en: 'Micronutrients (Fe, Mn, Zn, Cu, B)', es: 'Micronutrientes (Fe, Mn, Zn, Cu, B)' },
        defaultUnitId: 'mg_kg',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: ['element'],
        sao: {
            matrix: 'solo',
            tier: 'recommended',
            subcategory: 'chemical_soil',
            regulatoryRefs: ['EMBRAPA', 'IAC'],
            scenarios: ['deforestation', 'routine_monitoring'],
        },
    },
    {
        id: 'soil_cn_ratio',
        name: 'Relacao C:N',
        names: { en: 'C:N Ratio', es: 'Relacion C:N' },
        defaultUnitId: 'none',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: [],
        sao: {
            matrix: 'solo',
            tier: 'recommended',
            subcategory: 'chemical_soil',
            regulatoryRefs: ['EMBRAPA'],
            scenarios: ['deforestation', 'mining_operations', 'routine_monitoring'],
        },
    },

    // --- contamination_soil ---
    {
        id: 'soil_pahs',
        name: 'PAHs (Hidrocarbonetos Policiclicos Aromaticos) no Solo',
        names: {
            en: 'PAHs (Polycyclic Aromatic Hydrocarbons) in Soil',
            es: 'HAPs (Hidrocarburos Aromaticos Policiclicos) en Suelo',
        },
        defaultUnitId: 'ug_kg',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: ['detection_limit', 'cas_number'],
        sao: {
            matrix: 'solo',
            tier: 'recommended',
            subcategory: 'contamination_soil',
            regulatoryRefs: ['CONAMA 420/2009', 'CETESB 2021'],
            scenarios: ['chemical_accident', 'mining_operations', 'routine_monitoring'],
        },
    },
    {
        id: 'soil_pcbs',
        name: 'PCBs (Bifenilas Policloradas) no Solo',
        names: { en: 'PCBs (Polychlorinated Biphenyls) in Soil', es: 'PCBs (Bifenilos Policlorados) en Suelo' },
        defaultUnitId: 'ug_kg',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: ['detection_limit', 'congener'],
        sao: {
            matrix: 'solo',
            tier: 'recommended',
            subcategory: 'contamination_soil',
            regulatoryRefs: ['CONAMA 420/2009'],
            scenarios: ['chemical_accident', 'routine_monitoring'],
        },
    },
    {
        id: 'soil_pesticides',
        name: 'Agrotoxicos no Solo',
        names: { en: 'Pesticides in Soil', es: 'Plaguicidas en Suelo' },
        defaultUnitId: 'ug_kg',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: ['detection_limit', 'cas_number', 'active_ingredient'],
        sao: {
            matrix: 'solo',
            tier: 'recommended',
            subcategory: 'contamination_soil',
            regulatoryRefs: ['CONAMA 420/2009', 'CETESB 2021'],
            scenarios: ['deforestation', 'chemical_accident', 'routine_monitoring'],
        },
    },

    // --- biology_soil ---
    {
        id: 'soil_basal_respiration',
        name: 'Respiracao Basal do Solo',
        names: { en: 'Soil Basal Respiration', es: 'Respiracion Basal del Suelo' },
        defaultUnitId: 'mg_CO2_kg_h',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: [],
        sao: {
            matrix: 'solo',
            tier: 'recommended',
            subcategory: 'biology_soil',
            regulatoryRefs: ['ISO 16072'],
            scenarios: ['tailings_dam', 'mining_operations', 'deforestation', 'routine_monitoring'],
        },
    },
    {
        id: 'soil_microbial_biomass_c',
        name: 'Carbono da Biomassa Microbiana',
        names: { en: 'Microbial Biomass Carbon', es: 'Carbono de Biomasa Microbiana' },
        defaultUnitId: 'mg_kg',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: [],
        sao: {
            matrix: 'solo',
            tier: 'recommended',
            subcategory: 'biology_soil',
            regulatoryRefs: ['ISO 14240-2'],
            scenarios: ['tailings_dam', 'mining_operations', 'deforestation', 'routine_monitoring'],
        },
    },
    {
        id: 'soil_qco2',
        name: 'Quociente Metabolico (qCO2)',
        names: { en: 'Metabolic Quotient (qCO2)', es: 'Cociente Metabolico (qCO2)' },
        defaultUnitId: 'mg_CO2_kg_h',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: [],
        sao: {
            matrix: 'solo',
            tier: 'recommended',
            subcategory: 'biology_soil',
            regulatoryRefs: ['Anderson & Domsch 1978'],
            scenarios: ['tailings_dam', 'mining_operations', 'deforestation', 'routine_monitoring'],
        },
    },

    // --- erosion ---
    {
        id: 'soil_erosion_rate',
        name: 'Taxa de Erosao Laminar',
        names: { en: 'Sheet Erosion Rate', es: 'Tasa de Erosion Laminar' },
        defaultUnitId: 't_ha_yr',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: ['usle_factors'],
        sao: {
            matrix: 'solo',
            tier: 'recommended',
            subcategory: 'erosion',
            regulatoryRefs: ['USLE/RUSLE', 'EMBRAPA'],
            scenarios: ['tailings_dam', 'mining_operations', 'deforestation', 'routine_monitoring'],
        },
    },

    // ─── SPECIALIZED ─────────────────────────────────────────

    // --- biology_soil ---
    {
        id: 'soil_dehydrogenase',
        name: 'Atividade da Desidrogenase',
        names: { en: 'Dehydrogenase Activity', es: 'Actividad de la Deshidrogenasa' },
        defaultUnitId: 'ug_kg',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: [],
        sao: {
            matrix: 'solo',
            tier: 'specialized',
            subcategory: 'biology_soil',
            regulatoryRefs: ['ISO 23753-1'],
            scenarios: ['tailings_dam', 'mining_operations', 'chemical_accident'],
        },
    },
    {
        id: 'soil_phosphatase',
        name: 'Atividade da Fosfatase',
        names: { en: 'Phosphatase Activity', es: 'Actividad de la Fosfatasa' },
        defaultUnitId: 'ug_kg',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: [],
        sao: {
            matrix: 'solo',
            tier: 'specialized',
            subcategory: 'biology_soil',
            regulatoryRefs: ['Tabatabai & Bremner 1969'],
            scenarios: ['tailings_dam', 'mining_operations', 'deforestation'],
        },
    },
    {
        id: 'soil_urease',
        name: 'Atividade da Urease',
        names: { en: 'Urease Activity', es: 'Actividad de la Ureasa' },
        defaultUnitId: 'ug_kg',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: [],
        sao: {
            matrix: 'solo',
            tier: 'specialized',
            subcategory: 'biology_soil',
            regulatoryRefs: ['Kandeler & Gerber 1988'],
            scenarios: ['mining_operations', 'deforestation'],
        },
    },
    {
        id: 'soil_beta_glucosidase',
        name: 'Atividade da beta-Glucosidase',
        names: { en: 'beta-Glucosidase Activity', es: 'Actividad de la beta-Glucosidasa' },
        defaultUnitId: 'ug_kg',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: [],
        sao: {
            matrix: 'solo',
            tier: 'specialized',
            subcategory: 'biology_soil',
            regulatoryRefs: ['Eivazi & Tabatabai 1988'],
            scenarios: ['mining_operations', 'deforestation'],
        },
    },
    {
        id: 'soil_mesofauna',
        name: 'Mesofauna do Solo (Acaros, Colembolos)',
        names: { en: 'Soil Mesofauna (Mites, Springtails)', es: 'Mesofauna del Suelo (Acaros, Colembolos)' },
        defaultUnitId: 'none',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: ['ind_m2', 'taxa_richness'],
        sao: {
            matrix: 'solo',
            tier: 'specialized',
            subcategory: 'biology_soil',
            regulatoryRefs: ['ISO 23611-2'],
            scenarios: ['tailings_dam', 'mining_operations', 'deforestation'],
        },
    },
    {
        id: 'soil_macrofauna',
        name: 'Macrofauna do Solo (Minhocas, Larvas)',
        names: { en: 'Soil Macrofauna (Earthworms, Larvae)', es: 'Macrofauna del Suelo (Lombrices, Larvas)' },
        defaultUnitId: 'none',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: ['ind_m2', 'taxa_richness'],
        sao: {
            matrix: 'solo',
            tier: 'specialized',
            subcategory: 'biology_soil',
            regulatoryRefs: ['ISO 23611-1', 'TSBF method'],
            scenarios: ['tailings_dam', 'mining_operations', 'deforestation'],
        },
    },
    {
        id: 'soil_metagenomics',
        name: 'Metagenômica (16S rRNA)',
        names: { en: 'Metagenomics (16S rRNA)', es: 'Metagenomica (16S rRNA)' },
        defaultUnitId: 'none',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: ['sequencing_platform', 'primer_set'],
        sao: {
            matrix: 'solo',
            tier: 'specialized',
            subcategory: 'biology_soil',
            regulatoryRefs: [],
            scenarios: ['tailings_dam', 'mining_operations', 'deforestation'],
        },
    },

    // --- contamination_soil ---
    {
        id: 'soil_sequential_extraction',
        name: 'Extracao Sequencial (BCR/Tessier)',
        names: { en: 'Sequential Extraction (BCR/Tessier)', es: 'Extraccion Secuencial (BCR/Tessier)' },
        defaultUnitId: 'mg_kg',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: ['fraction', 'target_metal'],
        sao: {
            matrix: 'solo',
            tier: 'specialized',
            subcategory: 'contamination_soil',
            regulatoryRefs: ['BCR Protocol', 'Tessier 1979'],
            scenarios: ['tailings_dam', 'mining_operations', 'chemical_accident'],
        },
    },
    {
        id: 'soil_pfas',
        name: 'PFAS (Substancias Per/Polifluoroalquil) no Solo',
        names: {
            en: 'PFAS (Per/Polyfluoroalkyl Substances) in Soil',
            es: 'PFAS (Sustancias Per/Polifluoroalquilicas) en Suelo',
        },
        defaultUnitId: 'ng_g',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: ['detection_limit', 'compound'],
        sao: {
            matrix: 'solo',
            tier: 'specialized',
            subcategory: 'contamination_soil',
            regulatoryRefs: ['US EPA Method 533'],
            scenarios: ['chemical_accident', 'routine_monitoring'],
        },
    },

    // --- mineralogy ---
    {
        id: 'soil_xrd',
        name: 'Difracao de Raios X (DRX)',
        names: { en: 'X-Ray Diffraction (XRD)', es: 'Difraccion de Rayos X (DRX)' },
        defaultUnitId: 'none',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: ['mineral_phases'],
        sao: {
            matrix: 'solo',
            tier: 'specialized',
            subcategory: 'mineralogy',
            regulatoryRefs: [],
            scenarios: ['tailings_dam', 'mining_operations'],
        },
    },
    {
        id: 'soil_xrf',
        name: 'Fluorescencia de Raios X (FRX)',
        names: { en: 'X-Ray Fluorescence (XRF)', es: 'Fluorescencia de Rayos X (FRX)' },
        defaultUnitId: 'percent',
        type: 'SI',
        category: 'contaminant',
        allowedCustomFields: ['element_oxide'],
        sao: {
            matrix: 'solo',
            tier: 'specialized',
            subcategory: 'mineralogy',
            regulatoryRefs: [],
            scenarios: ['tailings_dam', 'mining_operations'],
        },
    },
];
